"""File that consists constant values."""

DOMAIN = "papouch"
DEFAULT_SCAN_INTERVAL = 10
DEFAULT_BAUDRATE = 9600
AUTH_FAILED_ERROR = 401
DEFAULT_WEB_PORT = 80
UNKNOWN_LOCATION = "NONANE"
UNKNOWN_NAME = "Unknown"

TCP_SERVER_MODE_INDEX = 0
TCP_CLIENT_MODE_INDEX = 1
UDP_MODE_INDEX = 2
WEB_MODE_INDEX = 3

DHCP_TIMEOUT = 5
